"""Generate Appendix C (campaign details) LaTeX tables from the committed data/ record.

Emits docs/aij_paper/appendix_campaign.tex with:
  B.1  per-cell aggregates for Experiment 1 (data/exp1_v2, balanced + imbalance arms):
       mean +/- sd MCC_FULL, completions/runs, median train time, per (sem, q, p, arm, f)
  B.2  the failure-taxonomy ledger: TIMED_OUT / UNSAT / ERROR counts per campaign
  B.3  breadth regimes (data/v3_*): same aggregates, one compact table per regime

Aggregation conventions are IDENTICAL to make_figs.py: MCC_FULL, OK rows only
(ILASP_TRAIN_SUCCEEDED == 1 and not TIMED_OUT), GRD excluded from exp1_v2.
Run: python3 docs/aij_paper/make_appendix_tables.py
"""
import csv, glob, os, re, statistics as st
from collections import defaultdict

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(REPO, "docs/aij_paper/appendix_campaign.tex")


def load(root):
    rows = []
    for f in glob.glob(f"{REPO}/data/{root}/results/**/results_*.csv", recursive=True):
        d = os.path.basename(os.path.dirname(f))
        m = re.match(r"([A-Z_]+)_partial_([0-9_]+)_noise_([0-9_]+)_ratio_(\w+)", d)
        if not m:
            continue
        sem, pa, no, arm = m.group(1), m.group(2).replace("_", "."), m.group(3).replace("_", "."), m.group(4)
        for r in csv.DictReader(open(f), delimiter=";"):
            r["_sem"], r["_p"], r["_q"], r["_arm"] = sem, pa, no, arm
            rows.append(r)
    return rows


def ok(r):
    return r.get("ILASP_TRAIN_SUCCEEDED") == "1" and r.get("ILASP_TRAIN_TIMED_OUT") != "1"


ARM = {"1": "50\\%", "40pos": "40\\%", "60pos": "60\\%"}


def cell_rows(rows):
    """group -> list; key = (sem, q, p, arm, f)"""
    by = defaultdict(list)
    for r in rows:
        by[(r["_sem"], r["_q"], r["_p"], r["_arm"], int(r["NFILES_POS"]))].append(r)
    return by


def agg_line(key, rs):
    sem, q, p, arm, f = key
    v = [float(r["MCC_FULL"]) for r in rs if ok(r) and r.get("MCC_FULL")]
    t = [float(r["RUNNING_TIME_ILASP_TRAIN_SECONDS"]) for r in rs
         if ok(r) and r.get("RUNNING_TIME_ILASP_TRAIN_SECONDS")]
    if v:
        mcc = f"{st.mean(v):.3f}" + (f" $\\pm$ {st.stdev(v):.3f}" if len(v) > 1 else "")
        med = f"{st.median(t):.0f}"
    else:
        mcc, med = "---", "---"
    return (f"{sem.replace('_', chr(92) + '_')} & {q} & {p} & "
            f"{ARM.get(arm, arm)} & {f} & {mcc} & "
            f"{len(v)}/{len(rs)} & {med}\\\\")


def taxonomy(rows):
    to = sum(1 for r in rows if r.get("ILASP_TRAIN_TIMED_OUT") == "1")
    un = sum(1 for r in rows if r.get("ILASP_TRAIN_UNSAT") == "1")
    er = sum(1 for r in rows if r.get("ILASP_TRAIN_ERROR") not in (None, "", "0"))
    okn = sum(1 for r in rows if ok(r))
    return len(rows), okn, to, un, er



def wide_table(rows, label=None):
    """Wide per-cell table: one row per (sem, q, p, arm), f values as columns."""
    by = defaultdict(list)
    fvals = sorted({int(r["NFILES_POS"]) for r in rows})
    for r in rows:
        by[(r["_sem"], r["_q"], r["_p"], r["_arm"], int(r["NFILES_POS"]))].append(r)
    groups = sorted({k[:4] for k in by})
    out = ["{\\scriptsize", "\\begin{longtable}{llll" + "c" * len(fvals) + "}",
           "\\toprule",
           "Sem. & $q$ & $p$ & arm & " +
           " & ".join(f"$f{{=}}{f}$" for f in fvals) + "\\\\",
           "\\midrule", "\\endhead", "\\bottomrule", "\\endfoot"]
    for g in groups:
        sem, q, p, arm = g
        cells = []
        for f in fvals:
            rs = by.get((*g, f), [])
            v = [float(r["MCC_FULL"]) for r in rs if ok(r) and r.get("MCC_FULL")]
            if not rs:
                cells.append("---")
                continue
            if not v:
                cells.append(f"---$^{{(0/{len(rs)})}}$")
                continue
            t = f"{st.mean(v):.2f}"
            if len(v) > 1:
                t += f"$\\pm${st.stdev(v):.2f}"
            if len(v) < len(rs):
                t += f"$^{{({len(v)})}}$"
            cells.append(t)
        out.append(f"{sem.replace('_', chr(92) + '_')} & {q} & {p} & "
                   f"{ARM.get(arm, arm)} & " + " & ".join(cells) + "\\\\")
    out += ["\\end{longtable}}"]
    return "\n".join(out)


def main():
    parts = []
    parts.append("% AUTO-GENERATED by make_appendix_tables.py from the committed data/ record.")
    parts.append("% Do not edit by hand; re-run the script instead.")

    # ---- C.1 Experiment 1 per-cell table (wide: f as columns)
    v2 = [r for r in load("exp1_v2") if r["_sem"] != "GRD"]
    parts.append("""
\\subsection*{B.1\\quad Experiment 1: per-cell aggregates}
Mean $\\pm$ s.d.\\ MCC on the complete-information surface over completed runs
(5 folds per cell); a superscript $(k)$ marks cells where only $k<5$ runs
completed (all exclusions are timeouts; B.2). Aggregation conventions are
identical to the body's tables; the generating script
(\\texttt{docs/aij\\_paper/make\\_appendix\\_tables.py}) recomputes every row
from the committed \\texttt{data/} record.
""")
    parts.append(wide_table(v2, label=None))
    # ---- C.2 taxonomy ledger
    parts.append("""
\\subsection*{B.2\\quad Failure-taxonomy ledger}
Disjoint counts per campaign (a run is OK, timed out, unsatisfiable, or
errored; the taxonomy is first-class and never folded into scores):

\\begin{center}\\small
\\begin{tabular}{lccccc}
\\toprule
Campaign & runs & OK & timed out & UNSAT & error\\\\
\\midrule""")
    for name, root, drop_grd in [("Experiment 1 (dense)", "exp1_v2", True),
                                 ("Breadth: sparse", "v3_sparse", False),
                                 ("Breadth: self-attack", "v3_self", False),
                                 ("Breadth: large ($n\\le12$)", "v3_large", False),
                                 ("Breadth: BAF", "v3_baf", False),
                                 ("Breadth: ABA", "v3_aba", False)]:
        rows = load(root)
        if drop_grd:
            rows = [r for r in rows if r["_sem"] != "GRD"]
        n, okn, to, un, er = taxonomy(rows)
        parts.append(f"{name} & {n} & {okn} & {to} & {un} & {er}\\\\")
    parts.append("""\\bottomrule
\\end{tabular}
\\end{center}""")

    # ---- C.3 breadth per-cell tables (wide)
    parts.append("""
\\subsection*{B.3\\quad Breadth regimes: per-cell aggregates}
Same conventions as B.1, one block per regime.
""")
    for root, title in [("v3_sparse", "Sparse generator"),
                        ("v3_self", "Self-attacking generator"),
                        ("v3_large", "Large ($n\\le12$) generator"),
                        ("v3_baf", "BAF"), ("v3_aba", "ABA")]:
        parts.append(f"\\paragraph{{{title}}}")
        parts.append(wide_table(load(root), label=None))
    # ---- C.4 exact invocations
    cfgs = sorted(os.path.basename(p) for p in
                  glob.glob(f"{REPO}/experiments/run_configs/*.json"))
    cfg_list = ", ".join(c.replace("_", "\\_") for c in cfgs)
    parts.append(f"""
\\subsection*{{B.4\\quad Exact invocations}}
Every run is reproducible from the seeded configuration files in
\\texttt{{experiments/run\\_configs/}} ({cfg_list}), executed by
\\texttt{{experiments/run\\_experiment\\_grid.py}} via the launchers
\\texttt{{run\\_v2\\_campaign.sh}}, \\texttt{{run\\_v3\\_gap.sh}}, and
\\texttt{{run\\_large\\_safe.sh}} (workers$=$1 plus a memory watchdog for the
$n\\le12$ regime). Master seed $20260309$; ILASP~4.4.1 with the flags of
\\texttt{{config/ilasp\\_config.json}}; clingo~5.x; train timeout
$3{{,}}500$\\,s. Both launchers are stop/resume-safe.""")

    open(OUT, "w").write("\n".join(parts) + "\n")
    print("wrote", OUT, f"({os.path.getsize(OUT)//1024} KB)")


if __name__ == "__main__":
    main()
